### ISSUE TITLE
Multiple création de classes

### ISSUE THREAD

**Issue by Aexelion** [Aexelion/Mini-Editeur#2]
Je pense qu'il faudra, avant le rendu final, supprimer les classes/interfaces qui ne sont pas modifiées d'une version à l'autre : 
- [ ] Affiche.java (V2/V3)
- [ ] IHM.java et ImplIHMText.java (V2/V3)
- [ ] Moteur.java et ImplMoteur.java (V2/V3)
- [ ] Buffer.java, PressePapier.java et Selection.java (V2/V3)
- [ ] Commande.java (V2/V3) et CommandeEnregistrable.java (V3)
- [ ] Enregistrable.java (V3)
- [ ] Enregistreur.java et ImplEnregistreur.java (V3)
- [ ] Memento.java, MementoInserer.java et MementoSelectionner.java (V3)

**Comment by Heartbroken-Git** [comment]
Perso je pense que garder l'arborescence telle qu'elle est c'est pas mal.
Au moins on a une séparation claire et pas d'importations à gérer. Mais à
voir ;)

**Comment by Aexelion** [comment]
Il faudra voir avec le prof mais garder tout un tas de fonctions qui ne changent, je suis pas sur que ce soit utile

**Comment by Heartbroken-Git** [comment]
Certes

**Comment by Aexelion** [comment]
Bon bah, plus le temps de voir ça avec le prof. De toute façon pour la séparation en version c'est plus pratique d'avoir la duplication quand même.
